### ISSUE TITLE
Add Double Decker Navigation

### ISSUE THREAD

**Issue by cjhowald** [zalando-incubator/solution-center-header#110]
We need to support double decker navigation in the Solution Center:

![image](https://cloud.githubusercontent.com/assets/14326547/18504143/1a2178d8-7a61-11e6-932e-2b26c0c601a4.png)

See [the Zeplin design](https://app.zeplin.io/project.html#pid=5774da90a782207029899386&sid=57d67bb89ee9c4137b65251b) for more details.
- [ ] Add second layer to header template #104 
- [ ] Add hover behavior #106 and styling #101 for products 
- [ ] Rework existing dropdowns #105 
- [ ] Handle special case where all modules are the same product #102 
- [ ] Handle special case in Solution Center (no module selected) #103

**Comment by gregdeane** [comment]
To be done in solution-center-navigation.
